//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kumari_cinema_web.pages
{


    public partial class Dashboard
    {
        protected global::System.Web.UI.WebControls.Label lblTotalUsers;
        protected global::System.Web.UI.WebControls.Label lblTotalMovies;
        protected global::System.Web.UI.WebControls.Label lblTotalBookings;
        protected global::System.Web.UI.WebControls.Label lblCurrentlyShowing;
        protected global::System.Web.UI.WebControls.Label lblTotalTheatres;
        protected global::System.Web.UI.WebControls.Button btnViewReport;
        protected global::System.Web.UI.WebControls.Panel ReportPanel;
        protected global::System.Web.UI.WebControls.TextBox txtReportUserId;
        protected global::System.Web.UI.WebControls.Button btnReportSearch;
        protected global::System.Web.UI.WebControls.Label lblReportMessage;
        protected global::System.Web.UI.WebControls.GridView GridViewReportTickets;
        protected global::System.Web.UI.WebControls.DropDownList ddlReportTheaterCityHall;
        protected global::System.Web.UI.WebControls.Button btnReportFilterTheater;
        protected global::System.Web.UI.WebControls.Label lblReportTheaterMessage;
        protected global::System.Web.UI.WebControls.GridView GridViewReportTheater;
        protected global::System.Web.UI.WebControls.GridView GridViewReportOccupancy;
    }
}
